name: Update flow file
env:
  FLOW_CONTENT: ""
on:
  workflow_dispatch:
    inputs:
      task_id:
        description: 'the id of the task which is associated to the flow file'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Install python dependencies
        run: pip install requests
      - name: Send flowfile content to production
        uses: jannekem/run-python-script-action@v1
        env:
          AUTH_TOKEN: ${{ secrets.FLOW_AUTH_TOKEN }}
          FLOW_BASE_URL: ${{ secrets.FLOW_BASE_URL }}
          TASK_ID: ${{ github.event.inputs.task_id }}
        with:
          script: |
            import requests
            import os
            
            BASE_API_URL = os.getenv("FLOW_BASE_URL", "")
            AUTH_TOKEN = os.getenv("AUTH_TOKEN", "")
            TASK_ID = os.getenv("TASK_ID","")
            content = ""
            
            with open("flowfile.xml", "r", encoding="utf-8") as file:
              content = file.read()
            
            requests.post(
              url=f"{BASE_API_URL}/api/task/{TASK_ID}/update_flow_file/",
              headers={"Authorization": f"Token {AUTH_TOKEN}"},
              data={"content": content},
            )
            

