name: Update flow file
env:
  FLOW_CONTENT: ""
on:
  workflow_dispatch:
    inputs:
      task_id:
        description: 'the id of the task which is associated to the flow file'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Read flow file content
        id: readflowcontent
        run: |
          input_file="flowfile.xml"
          while read line
          do
            file_text=$line
          done < "$input_file"
          echo ::set-output name=content::$file_text
      - name: Update flow file in production
        run: |
          curl -X POST ${{ secrets.FLOW_BASE_URL }}/api/task/${{ github.event.inputs.task_id }}/update_flow_file/ --header 'Authorization: Token ${{ secrets.FLOW_AUTH_TOKEN }}' --data '{"content":"${{ steps.readflowcontent.outputs.content }}"}' -H "Content-Type: application/json"  
