
name: Update flow file

on:
  workflow_dispatch:
    inputs:
      task_id:
        description: 'the id of the task which is associated to the flow file'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@master
    - name: Read flow file content
      id: readflowcontent
      run: echo "::set-output name=version::$(cat flowfile.xml)"
    - name: Update flow file in production
      run: |
        curl -X POST ${{ secrets.FLOW_BASE_URL }}/api/task/${{ github.event.inputs.task_id }}/update_flow_file/ --header 'Authorization: Token ${{ secrets.FLOW_AUTH_TOKEN }}' --data '{"content":"${{ steps.readflowcontent.outputs.version }}"}' 
