name: Update flow file
env:
  FLOW_CONTENT: ""
on:
  workflow_dispatch:
    inputs:
      task_id:
        description: 'the id of the task which is associated to the flow file'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Read flowfile
        id: read_flow_content
        uses: juliangruber/read-file-action@v1
        with:
          path: ./flowfile.xml
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.FLOW_BASE_URL }}/api/task/${{ github.event.inputs.task_id }}/update_flow_file/
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Authorization": "Token ${{ secrets.FLOW_AUTH_TOKEN }}"}'
          data: '{"content": "${{ steps.read_flow_content.outputs.content }}"}'
